"use client";

import { Footer, Nav, SectionLabel } from "@/components/site";

export default function Terms() {
  return (
    <>
      <Nav />
      <main className="legal-main-shell">
        <div className="legal-header-block">
          <SectionLabel index="02">LEGAL & OPERATIONS</SectionLabel>
          <h1 className="legal-main-title">Terms of Service & Usage Charter</h1>
          <p className="legal-lead-text">
            Civitas organizes and synthesizes civic incident reports for municipal departments. It operates as an evidence intelligence assistant with mandatory human oversight.
          </p>
          <span className="last-updated-pill">Operational Charter · Version 1.0</span>
        </div>

        <div className="legal-sections-grid">
          <article className="legal-card emergency-warning">
            <span className="card-kicker warn">CRITICAL SAFETY NOTICE</span>
            <h2>01. Not for Emergency Services</h2>
            <p>
              Civitas is designed for non-emergency municipal infrastructure maintenance (potholes, water leaks, streetlight outages, drainage blockages).
            </p>
            <p>
              For life-threatening emergencies, active fires, gas leaks, medical crises, or violent crimes, immediately call your local emergency dispatch number (e.g. 911 / 112 / 100). Do not rely on an automated civic queue.
            </p>
          </article>

          <article className="legal-card">
            <span className="card-kicker">ACCURACY CHARTER</span>
            <h2>02. Citizen Submission Honesty</h2>
            <p>
              Users are expected to submit reports that they reasonably believe to be accurate and factual. Submitting intentionally fraudulent reports or fabricating emergency scenarios is strictly prohibited.
            </p>
          </article>

          <article className="legal-card">
            <span className="card-kicker">OPERATIONAL BOUNDARY</span>
            <h2>03. Non-Binding Estimated Timelines</h2>
            <p>
              Estimated resolution windows (e.g. 8–14 hours) generated by the system are non-binding operational estimates based on historical municipal playbooks. They do not constitute a legal contract or municipal guarantee.
            </p>
          </article>

          <article className="legal-card">
            <span className="card-kicker">OPEN PLATFORM</span>
            <h2>04. Platform Availability & Architecture</h2>
            <p>
              Civitas is provided on an &apos;as-available&apos; basis. The system operates with transparent LangGraph checkpoints, PostgreSQL persistence, and fail-safe human supervisor gates.
            </p>
          </article>
        </div>
      </main>
      <Footer />

      <style jsx>{`
        .legal-main-shell {
          width: min(calc(100% - 40px), 980px);
          margin: 36px auto 100px;
        }
        .legal-header-block {
          padding-bottom: 28px;
          border-bottom: 2px solid #172019;
          margin-bottom: 36px;
        }
        .legal-main-title {
          font-size: clamp(2.4rem, 4.5vw, 3.8rem);
          font-family: Georgia, serif;
          margin: 8px 0 12px;
          color: #172019;
          line-height: 1;
        }
        .legal-lead-text {
          font-size: 1.05rem;
          color: #555e54;
          line-height: 1.6;
          margin: 0 0 16px;
        }
        .last-updated-pill {
          font-size: 0.68rem;
          font-weight: 850;
          background: #dce8dd;
          color: #0f5f4f;
          padding: 4px 10px;
          border-radius: 4px;
          display: inline-block;
        }
        .legal-sections-grid {
          display: flex;
          flex-direction: column;
          gap: 24px;
        }
        .legal-card {
          border: 1px solid #172019;
          background: #ffffff;
          box-shadow: 4px 4px 0 #172019;
          padding: 28px;
        }
        .emergency-warning {
          border-left: 6px solid #e84d7a;
          background: #fff8f8;
        }
        .card-kicker {
          font-size: 0.6rem;
          font-weight: 900;
          letter-spacing: 0.12em;
          color: #0f5f4f;
          display: block;
          margin-bottom: 6px;
        }
        .card-kicker.warn {
          color: #e84d7a;
        }
        .legal-card h2 {
          font-size: 1.35rem;
          font-family: Georgia, serif;
          margin: 0 0 12px;
          color: #172019;
        }
        .legal-card p {
          font-size: 0.9rem;
          color: #495248;
          line-height: 1.65;
          margin: 0 0 12px;
        }
        .legal-card p:last-child {
          margin-bottom: 0;
        }
      `}</style>
    </>
  );
}
