import { DocsPage } from "@/components/site";

type Block = { heading: string; body: string; bullets?: string[]; code?: string };
type Doc = { title: string; intro: string; blocks: Block[] };

const core: Block[] = [
  { heading: "Operating principle", body: "Civitas treats a civic report as evidence that requires interpretation, not as an instruction that should automatically create a municipal action. It preserves the difference between what a resident reported, what media appears to show, context retrieved from systems or policy, and conclusions made by tools or agents. This boundary is carried into traces, review screens and citizen communication." },
  { heading: "Typed contracts", body: "Public API envelopes, ML outputs, workflow state, knowledge evidence and review actions are schema-validated. Typed contracts make failures visible at a boundary instead of allowing malformed data to move quietly into a later decision. A schema is also how the web product can safely render status without depending on private workflow internals." },
  { heading: "Failure behavior", body: "A missing report, unavailable ML result, malformed structured output, insufficient municipal evidence or invalid review transition is a first-class state. Civitas records warnings and errors, stops or requests review when needed, and does not replace missing evidence with a plausible response." },
  { heading: "Traceability", body: "Each meaningful node can retain a trace identifier, tool or model name, status, latency, retry count, validation result and referenced knowledge IDs. Secrets, authorization headers, unnecessary raw private data and hidden chain-of-thought are not recorded as operational trace content." },
];

const docs: Record<string, Doc> = {
  "": { title: "Civitas system guide", intro: "A practical engineering reference for the product path from citizen report to a reviewed municipal recommendation.", blocks: [{ heading: "What the system connects", body: "Civitas joins report intake, media and location context, deterministic ML, municipal knowledge retrieval, agentic reasoning, work-order planning, human review and resident updates. These capabilities are connected by a typed workflow rather than one universal prompt." }, { heading: "Who uses it", body: "Residents supply a report and can answer a focused clarification. Municipal reviewers see routing, supporting evidence and operational recommendations. Service owners operate the API, knowledge corpus, model configuration and checkpoint infrastructure." }, { heading: "Decision lifecycle", body: "A report first becomes structured evidence. Related reports can become a shared incident. ML and policy evidence support routing and planning. A critic checks the recommendation. High-impact action pauses for a reviewer before a safe citizen update is produced.", code: "report → evidence → ML + knowledge → routing → plan\n       → critic → human review → citizen update" }, ...core] },
  architecture: { title: "System architecture", intro: "Explicit boundaries keep the product testable, operationally comprehensible and safe to evolve.", blocks: [{ heading: "Runtime topology", body: "Next.js provides the product interface. FastAPI owns authentication, persistence, workflow execution and the internal ML bridge. PostgreSQL or Supabase holds application data and workflow metadata. LangGraph checkpoint state uses a PostgreSQL-compatible saver in production. Groq is accessed only through a provider-neutral client.", code: "Next.js product\n    ↓ typed envelopes\nFastAPI runtime ── LangGraph workflow\n    ├─ local ML + geospatial packages\n    ├─ KnowledgeService + policy APIs\n    └─ PostgreSQL / Supabase + checkpoints" }, { heading: "Why the ML bridge is internal", body: "The existing unified ReportAnalysis pipeline remains installed with the FastAPI runtime. The protected internal analyze route is a thin contract boundary, not a separately deployed ML microservice. This avoids duplicated model logic while preserving an adapter boundary for testing and composition." }, { heading: "Persistence split", body: "Workflow-run metadata maps a workflow ID, report ID, incident ID, trace ID, status and stable thread ID. It intentionally does not duplicate LangGraph checkpoint payloads. Canonical report, assessment, routing, work-order and review structures remain where the backend already owns them." }, { heading: "Composition", body: "Production composition wires Groq, HTTP-capable tools, persistence, trace handling and the durable saver. Test composition wires deterministic fakes and an in-memory saver. Graph logic is shared; only dependencies differ." }, ...core] },
  workflow: { title: "Workflow and operations", intro: "The graph turns a report into a reviewable recommendation through bounded nodes, explicit interrupts and idempotent resume behavior.", blocks: [{ heading: "Context and evidence", body: "The context loader deterministically normalizes report description, citizen category, coordinates, media metadata, existing incident links, clarification answers and persisted ML references. The evidence agent then produces strict structured output with observable facts, reported claims, hazards, landmarks, contradictions, uncertainty and missing information." }, { heading: "Deterministic intelligence", body: "Duplicate detection, cluster context, severity and priority are obtained through the ML intelligence tool. The workflow does not ask an LLM to recreate scores. Model metadata, uncertainty and feature contributions remain associated with the resulting state so a reviewer can distinguish model output from narrative interpretation." }, { heading: "Grounding, routing and planning", body: "Knowledge retrieval uses category, department, jurisdiction and policy-purpose filters before deterministic keyword ranking. Routing may interpret retrieved policy but every policy-dependent claim must cite a valid knowledge reference. Planning proposes actions, constraints and non-binding timing only when supported by playbooks or data." }, { heading: "Interrupt and resume", body: "Clarification questions are limited to decision-relevant information. When needed, the graph checkpoints and returns WAITING_FOR_CLARIFICATION. Human review similarly checkpoints at WAITING_FOR_REVIEW. Answers and reviewer actions resume the same stable thread; the graph is not rebuilt from the beginning." }, { heading: "Revision loop", body: "The critic returns PASS, REVISE, HUMAN_REVIEW_REQUIRED or ABSTAIN with concise machine-readable issues. Revision routes back only to the responsible node and has a bounded count. Repeated starts reuse active or completed runs to prevent duplicate work orders and duplicate decisions." }, ...core] },
  safety: { title: "Governance, safety and evaluation", intro: "Civitas is designed to expose uncertainty and preserve a human decision point rather than manufacture confidence.", blocks: [{ heading: "Evidence states", body: "The product maintains observed, reported, retrieved and inferred categories. An image-derived observation is not silently merged with a resident assertion, and an inference is never presented as municipal policy. Unknown fields remain unknown until supported evidence becomes available." }, { heading: "Knowledge abstention", body: "Knowledge outcomes are SUPPORTED, PARTIALLY_SUPPORTED or INSUFFICIENT_KNOWLEDGE. Missing policy does not authorize a fabricated jurisdiction rule. The workflow may continue with a limitation, request human review or abstain, depending on the decision impact." }, { heading: "Review controls", body: "Review actions are deliberately narrow: approve, edit, reroute, reject and request more evidence. Edit and reroute fields are validated against canonical schemas. Reject cannot create an approved final work order. Review intent and relevant state are persisted before resume." }, { heading: "Evaluation method", body: "The evaluation service compares a single competent prompt, a structured mega-prompt and the actual Civitas graph on the same 25-case corpus. Offline deterministic execution tests contracts and reproducibility; it is not presented as a live-model quality result. Live Groq execution is manual and records model, latency, usage and failures separately." }, { heading: "Useful measures", body: "Metrics include structured-output validity, category and department correctness, escalation, valid and fabricated policy references, unsupported municipal claims, work-order completeness, prohibited timeline promises, clarification and abstention correctness, review correctness, failures, latency and model calls. Percentages always carry the evaluated case count." }, ...core] },
  api: { title: "API and integration", intro: "The API provides typed operational boundaries for citizen reporting, workflow runtime, internal analysis and review actions.", blocks: [{ heading: "Envelope contract", body: "Endpoints return a shared success or error envelope. The web client validates the envelope before using data so an error response cannot be mistaken for a workflow state. Error types remain useful for UI messaging without leaking implementation details or secrets." }, { heading: "Workflow runtime", body: "POST /api/v1/reports/{report_id}/workflow starts or reuses an active run. GET /api/v1/workflows/{workflow_id} returns safe status and interrupt data. Clarification and review routes validate inputs, persist the action through backend-owned structures and resume the same graph thread.", code: "POST /api/v1/reports/{report_id}/workflow\nGET  /api/v1/workflows/{workflow_id}\nPOST /api/v1/workflows/{workflow_id}/clarification\nPOST /api/v1/workflows/{workflow_id}/review" }, { heading: "Internal ML analysis", body: "POST /api/v1/ml/analyze is protected by the existing internal authentication configuration. It loads stored report context where possible and returns the shared ML result contract: media intelligence, duplicate and cluster information, severity, priority, uncertainty, model metadata, warnings and trace ID." }, { heading: "Authorization and privacy", body: "Citizen actions must respect ownership and access rules. Municipal review requires an appropriate reviewer role. Internal routes cannot be anonymously exposed in production. Client-side location permission is optional and should be reviewed before report submission." }, { heading: "Deployment readiness", body: "Production configuration is environment-driven for API auth, database/checkpoint connection and Groq models. Readiness includes the state needed to serve runtime traffic; liveness alone does not prove that a workflow can safely execute." }, ...core] },
};

const legacy: Record<string, string> = { agents: "workflow", ml: "architecture", knowledge: "safety", evaluation: "safety", deployment: "api" };

export default async function Docs({ params }: { params: Promise<{ slug?: string[] }> }) {
  const { slug = [] } = await params;
  const key = legacy[slug[0] ?? ""] ?? slug[0] ?? "";
  const page = docs[key] ?? docs[""];
  return <DocsPage title={page.title} intro={page.intro}>{page.blocks.map((block, index) => <section className="doc-section" key={block.heading} id={`section-${index + 1}`}><div className="doc-section-number">{String(index + 1).padStart(2, "0")}</div><div><h2>{block.heading}</h2><p>{block.body}</p>{block.bullets && <ul>{block.bullets.map((bullet) => <li key={bullet}>{bullet}</li>)}</ul>}{block.code && <pre><code>{block.code}</code></pre>}</div></section>)}</DocsPage>;
}
