"use client";
import { useState } from "react";
import { Nav, Status } from "@/components/site";

const stages = [
  { label: "Reports arrive", short: "REPORTS", title: "Three residents describe the same place differently.", body: "One report is vague, one mentions bikes slipping near a school, and one video is submitted under the wrong category.", note: "Civitas starts with evidence, not the resident-selected label." },
  { label: "Evidence structured", short: "EVIDENCE", title: "What was seen, said and inferred stays separate.", body: "Visual observations are kept distinct from resident claims. Unknown cause remains unknown rather than being filled in by the model.", note: "Observed ≠ reported ≠ inferred." },
  { label: "Reports clustered", short: "INCIDENT", title: "Three reports become one operational incident.", body: "Geospatial, temporal and evidence signals identify related reports while guarding against same-location hard negatives.", note: "Municipal teams act on the incident, not three disconnected inbox items." },
  { label: "Priority set", short: "PRIORITY", title: "Severity and urgency are not treated as the same thing.", body: "School and traffic context raise operational priority even when the physical severity signal alone does not tell the whole story.", note: "Context changes what needs attention first." },
  { label: "Policy grounded", short: "GROUNDING", title: "Routing is supported by municipal playbooks.", body: "The knowledge layer retrieves relevant response and escalation guidance. Missing policy evidence causes abstention rather than invented rules.", note: "Recommendation cites PLAY-WATER-01." },
  { label: "Human review", short: "REVIEW", title: "A reviewer decides before operational commitment.", body: "Routing and work-order recommendations pause at a real LangGraph checkpoint. A reviewer can approve, edit, reroute, reject or request more evidence.", note: "Approval resumes the same persisted workflow thread." },
  { label: "Resident updated", short: "UPDATE", title: "The loop closes with a plain-language status update.", body: "After approval, Civitas communicates what was understood and what happens next without exposing internal reasoning or making unsupported promises.", note: "Resolution can later be verified against follow-up evidence." },
];

export default function Demo() {
  const [step, setStep] = useState(0);
  const stage = stages[step];
  return <><Nav /><main className="demo-shell"><header className="demo-header"><div><span className="workspace-kicker">GOLDEN SCENARIO / WATER LEAK</span><h1>See the decision take shape.</h1><p>Walk through the exact kind of multi-report incident Civitas was designed to handle.</p></div><Status tone="good">INTERACTIVE DEMO</Status></header>
    <div className="demo-grid"><aside className="demo-stepper">{stages.map((item, index) => <button onClick={() => setStep(index)} className={step === index ? "active" : step > index ? "passed" : ""} key={item.short}><span>{String(index + 1).padStart(2, "0")}</span><div><b>{item.short}</b><small>{item.label}</small></div></button>)}</aside>
    <section className="demo-stage"><div className="demo-stage-index"><span>{String(step + 1).padStart(2, "0")}</span><p>{stage.short}</p></div><h2>{stage.title}</h2><p className="stage-lede">{stage.body}</p>{step === 0 && <div className="demo-reports"><article><span>A · PHOTO</span><b>“Water on road near school.”</b><small>Category uncertain</small></article><article><span>B · TEXT</span><b>“Bikes are slipping by the gate.”</b><small>Safety + landmark context</small></article><article><span>C · VIDEO</span><b>Selected: pothole</b><small>Visual evidence points elsewhere</small></article></div>}{step === 2 && <div className="cluster-visual"><span>REPORT A</span><span>REPORT B</span><span>REPORT C</span><i>→</i><b>INC-0241</b></div>}{step === 3 && <div className="priority-visual"><div><span>Severity</span><b>Elevated</b></div><i>+</i><div><span>School context</span><b>Present</b></div><i>+</i><div><span>Traffic risk</span><b>Present</b></div><i>=</i><div className="result"><span>Priority</span><b>P1 · High</b></div></div>}{step === 4 && <div className="policy-card"><span>PLAY-WATER-01</span><b>Water leakage response playbook</b><p>Grounded policy reference retained with the routing recommendation.</p></div>}{step === 5 && <div className="review-demo"><b>Water department + traffic coordination</b><p>Inspect and isolate the active leak; secure the crossing during field inspection.</p><div><button>Approve</button><button>Edit</button><button>Reroute</button></div></div>}{step === 6 && <div className="citizen-message"><span>UPDATE TO REPORTERS</span><p>“Your report has been grouped with related reports near the school crossing and sent for municipal action. We’ll update this incident as its status changes.”</p></div>}<footer className="stage-footer"><span>WHY THIS MATTERS</span><b>{stage.note}</b><div><button disabled={step === 0} onClick={() => setStep((s) => Math.max(0, s - 1))}>← Previous</button><button onClick={() => setStep((s) => Math.min(stages.length - 1, s + 1))} disabled={step === stages.length - 1}>Next →</button></div></footer></section></div>
  </main></>;
}
