"use client";

import { FormEvent, useState } from "react";

export function OnboardingPanel({ onClose }: { onClose: () => void }) {
  const [step, setStep] = useState(1);
  const submit = (event: FormEvent) => { event.preventDefault(); if (step < 2) setStep(2); else onClose(); };
  return <div className="onboarding-backdrop" role="dialog" aria-modal="true" aria-labelledby="onboarding-title"><section className="onboarding-panel"><button className="onboarding-close" aria-label="Close onboarding" onClick={onClose}>×</button><p className="section-kicker">Welcome to Civitas · {step}/2</p><h2 id="onboarding-title">{step === 1 ? "A little about you." : "Set your local context."}</h2><p className="onboarding-copy">{step === 1 ? "This helps personalize your account. Required account verification happens only when authentication is connected." : "Your area helps keep local updates relevant. Precise location sharing is always optional."}</p><form onSubmit={submit}>{step === 1 ? <><label>Display name<input required autoComplete="name" placeholder="Your name" /></label><label>Email address<input required type="email" autoComplete="email" placeholder="you@example.com" /></label><label>Phone number <small>optional</small><input type="tel" autoComplete="tel" placeholder="Your preferred contact number" /></label></> : <><label>Area of residence<input required autoComplete="address-level2" placeholder="Ward, neighbourhood or city" /></label><label>How should updates reach you?<select defaultValue="email"><option value="email">Email</option><option value="sms">SMS when available</option><option value="none">Only in-app</option></select></label><div className="onboarding-notice"><b>Your control</b><p>You can edit these settings, decline location permission and remove local preview data later.</p></div></>}<div className="onboarding-actions">{step === 2 && <button type="button" className="text-button" onClick={() => setStep(1)}>Back</button>}<button className="button">{step === 1 ? "Continue" : "Finish setup"}</button></div></form></section></div>;
}
