import Link from "next/link";

import { Footer, Nav, SectionLabel } from "@/components/site";

const developers = [{ name: "Dhruv Gupta", role: "Product, agentic AI & integration", text: "Leads product direction, the LangGraph workflow, knowledge grounding, evaluation and runtime integration." }, { name: "Pavit Aggarwal", role: "Computer vision, ML & geospatial", text: "Builds the vision, duplicate reasoning, risk and resolution intelligence behind incident assessment." }, { name: "Utkarsh", role: "Backend & municipal operations", text: "Builds the FastAPI, persistence, routing, work-order, clarification and operational surfaces." }];

export default async function About({ params }: { params: Promise<{ section: string }> }) {
  const { section } = await params;
  if (section === "developers") return <><Nav /><main className="about-shell"><SectionLabel index="03">About / Team behind</SectionLabel><div className="about-hero"><h1>The people behind the system.</h1><p>Civitas is built across product, agentic reasoning, backend operations, computer vision, ML and geospatial intelligence — with each layer explicit enough to test on its own.</p></div><section className="mvp-note"><b>Hackathon MVP</b><p>Civitas is an early-stage hackathon MVP, not a full-scale municipal product yet. Some interactions use seeded data or local preview behavior because the project has limited time, infrastructure and operational resources. These constraints are visible rather than hidden behind a production claim.</p></section><section className="developer-list">{developers.map((dev, index) => <article key={dev.name}><span>{String(index + 1).padStart(2, "0")}</span><div><h2>{dev.name}</h2><b>{dev.role}</b><p>{dev.text}</p></div></article>)}</section></main><Footer /></>;
  if (section === "why") return <><Nav /><main className="about-shell"><SectionLabel index="02">About / Why</SectionLabel><div className="about-hero"><h1>The problem is not a lack of reports.</h1><p>It is the gap between receiving a report and turning it into a clear, defensible operational decision.</p></div><section className="problem-ledger">{[["01", "Reports arrive incomplete", "Residents describe what they see in normal language. They may not know the right category or department."], ["02", "Duplicates hide the real incident", "Several people can report the same problem differently, creating noise instead of one shared operational picture."], ["03", "Severity is not priority", "A physically moderate issue near a school or traffic crossing can need faster action than raw severity alone suggests."], ["04", "Routing needs evidence", "A department recommendation should be traceable to the incident evidence and relevant municipal playbooks."], ["05", "Residents lose visibility", "After submission, people often cannot see how their report became an incident, work order or resolution."]].map(([number, title, text]) => <article key={number}><span>{number}</span><h2>{title}</h2><p>{text}</p></article>)}</section><div className="about-next"><p>Civitas connects those handoffs without removing human judgment.</p><Link className="button secondary" href="/demo-workflow">See the workflow</Link></div></main><Footer /></>;
  return <><Nav /><main className="about-shell"><SectionLabel index="01">About / App</SectionLabel><div className="about-hero"><h1>A civic report should lead somewhere.</h1><p>Civitas turns scattered resident reports into structured incidents, grounded recommendations and reviewable municipal action.</p></div><section className="about-capabilities"><article><span>FOR RESIDENTS</span><h2>Report what you see.</h2><p>Describe the issue, attach media and location, answer a focused clarification if needed, then follow the incident rather than losing it in an inbox.</p></article><article><span>FOR MUNICIPAL TEAMS</span><h2>Review the decision, not raw noise.</h2><p>See related reports, evidence boundaries, severity and priority, policy-grounded routing, work-order planning and workflow trace in one place.</p></article></section><section className="about-pipeline"><span>REPORT</span><i>→</i><span>INCIDENT</span><i>→</i><span>GROUNDING</span><i>→</i><span>REVIEW</span><i>→</i><span>ACTION</span></section></main><Footer /></>;
}
