import { ReviewPanel } from "@/components/review-panel";
import { Nav, Status } from "@/components/site";

export default function Incident() {
  return <><Nav /><main className="incident-shell">
    <header className="incident-top"><div><span className="workspace-kicker">INC-0241 / WATER LEAKAGE</span><h1>Water leak near school crossing</h1><p>Three related resident reports have been consolidated into one operational incident.</p></div><div className="incident-state"><Status tone="warn">WAITING_FOR_REVIEW</Status><small>Trace CIV-TR-0241</small></div></header>
    <nav className="incident-tabs" aria-label="Incident sections"><a href="#evidence">Evidence</a><a href="#assessment">Assessment</a><a href="#routing">Routing</a><a href="#review">Review</a><a href="#trace">Trace</a></nav>
    <div className="incident-layout">
      <section className="incident-content">
        <section id="evidence" className="incident-section"><div className="section-title"><span>01</span><h2>Evidence</h2><p>Claims remain separated by source.</p></div><div className="evidence-grid"><article><span className="evidence-kind observed">OBSERVED</span><b>Standing water crosses part of the roadway.</b><p>Visual evidence from submitted media.</p></article><article><span className="evidence-kind reported">REPORTED</span><b>Resident says bikes are slipping near the school gate.</b><p>Citizen-provided claim, not treated as visual proof.</p></article><article><span className="evidence-kind inferred">INFERRED</span><b>Cause of leakage remains unknown.</b><p>Field inspection required before asserting source.</p></article></div><div className="report-sources"><span>REPORT A · PHOTO</span><span>REPORT B · TEXT</span><span>REPORT C · VIDEO</span></div></section>
        <section id="assessment" className="incident-section"><div className="section-title"><span>02</span><h2>Assessment</h2><p>ML outputs inform the workflow; they do not replace review.</p></div><div className="assessment-board"><div><span>Category</span><b>Water leakage</b><small>citizen selection corrected where needed</small></div><div><span>Cluster</span><b>3 related reports</b><small>same operational incident</small></div><div><span>Severity</span><b>Elevated</b><small>physical incident impact</small></div><div><span>Priority</span><b>P1 · High</b><small>school + traffic context raises urgency</small></div></div></section>
        <section id="routing" className="incident-section"><div className="section-title"><span>03</span><h2>Routing & plan</h2><p>Grounded recommendation prepared for municipal action.</p></div><div className="routing-line"><div><span>PRIMARY</span><b>Water department</b></div><i>→</i><div><span>COORDINATION</span><b>Traffic operations</b></div></div><div className="work-order"><span>WORK ORDER DRAFT</span><h3>Inspect and isolate the active leak; make the affected crossing safe.</h3><ul><li>Confirm leak source on site.</li><li>Secure the affected road area while inspection is underway.</li><li>Coordinate traffic handling around the school crossing.</li></ul><footer><b>Grounded by PLAY-WATER-01</b><span>Non-binding operational recommendation</span></footer></div></section>
      </section>
      <aside className="incident-aside"><div className="sticky-review" id="review"><ReviewPanel /><section id="trace" className="trace-card"><span>WORKFLOW TRACE</span>{["Evidence structured", "ML intelligence attached", "Knowledge grounded", "Routing proposed", "Critic passed", "Human review waiting"].map((item, index) => <div key={item}><i className={index < 5 ? "done" : "waiting"} /><p><b>{item}</b><small>{index < 5 ? "completed" : "current checkpoint"}</small></p></div>)}</section></div></aside>
    </div>
  </main></>;
}
